name: Claims
version: ${project.version}
main: claims.Main
api-version: 1.18
authors: [ Mason ]
depends: ['dynmap']
description: Claims Plugin
website: Masonking.dev
commands:
  claim:
    description: "Main claims command"
  unclaim:
    description: "Command to unclaim land"
